title:  jcalcutt.github.io
tagline:  __main__

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-112189500-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Posts', path: 'menu', url: 'writing.html'}
- {name: 'Projects', path: 'menu', url: 'projects.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/jcalcutt'}
# - {icon: 'twitter', link: 'https://twitter.com'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jordan-calcutt-16b348a7/'}
- {icon: 'envelope', link: 'mailto:jcalcutt7@gmail.com'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}
